name: oOf merging

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: http://download.h2os.com/OnePlus7T/OBT/OnePlus7THydrogen_13.X.07_OTA_007_all_2007030048_cdd72fc67d4b4884.zip
  ROM_NAME: OxygenOS
  ZIP_NAME: HydrogenOS
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get install wget
            sudo apt-get install p7zip-full
            sudo apt-get update -y
            sudo apt-get install -y simg2img  
            sudo apt-get install unzip
            sudo apt-get install zip gzip tar
            
       - name: Downloading system, product, and opproduct
         run: | 
              aria2c https://tdrive.manofuranium.workers.dev/OP7T/opproduct.img
              
       - name: making
         run: |
              sudo su
              mkdir lololo
              sudo mount -o loop opproduct.img lololo/
              cd lololo
              ls
              sudo zip -r dynamic7t.zip build.prop feature_list
              
       - name: upload ab n info
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit dynamic7t.zip
